FileToEmailLinker/Models/Services/Dashboard/DashboardService.cs
using FileToEmailLinker.Models.Services.Alert;
using FileToEmailLinker.Models.Services.Schedulation;
using FileToEmailLinker.Models.ViewModels;
using FileToEmailLinker.Models.ViewModels.Dashboard;

namespace FileToEmailLinker.Models.Services.Dashboard
{
    public class DashboardService : IDashboardService
    {
        private readonly ISchedulationService schedulationService;
        private readonly IConfiguration configuration;
        private readonly IAlertService alertService;

        public DashboardService(ISchedulationService schedulationService, IConfiguration configuration, IAlertService alertService)
        {
            this.schedulationService = schedulationService;
            this.configuration = configuration;
            this.alertService = alertService;
        }

        public async Task<Dictionary<DateOnly, ICollection<Entities.Schedulation>>> GetUpcomingSchedulations()
        {
            var today = DateOnly.FromDateTime(DateTime.Now.Date);
            Dictionary<DateOnly, ICollection<Entities.Schedulation>> schedulationDict = new Dictionary<DateOnly, ICollection<Entities.Schedulation>>();
            int schedulationCount = 0;
            int schedulationLimit = Int32.Parse(configuration["DashboardSchedulationLimit"] ?? "10");
            for (int i = 0; i < 365; i++)
            {
                if (schedulationCount < schedulationLimit)
                {
                    var date = today.AddDays(i);
                    var schedulations = await schedulationService.GetActiveSchedulationsByDateOrWeekDay(date);
                    if (schedulations.Count > 0)
                    {
                        schedulationDict.Add(date, schedulations.OrderBy(sched => sched.Time).ToList());
                        schedulationCount += schedulations.Count;
                    }
                }
            }
                    
            return schedulationDict;
        }

        public async Task<Dictionary<DateOnly, ICollection<Entities.Schedulation>>> GetSchedulationByDate(DateOnly date)
        {
            Dictionary<DateOnly, ICollection<Entities.Schedulation>> schedulationDict = new Dictionary<DateOnly, ICollection<Entities.Schedulation>>();
            var schedulations = await schedulationService.GetActiveSchedulationsByDateOrWeekDay(date);
            schedulationDict.Add(date, schedulations.OrderBy(sched => sched.Time).ToList());
            return schedulationDict;
        }

        public async Task<DashboardViewModel> GetDashboardViewModel()
        {
            DashboardViewModel model = new();
            Dictionary<DateOnly, ICollection<Entities.Schedulation>> upcomingSchedulations = await GetUpcomingSchedulations();
            AlertsListViewModel unvisualizedAlertList = await alertService.GetUnvisualizedAlertListViewModelAsync(1, 10);
            AlertsListViewModel visualizedAlertList = await alertService.GetVisualizedAlertListViewModelAsync(1, 10);
            model.SchedulationGroupList = upcomingSchedulations;
            model.UnvisualizedAlertList = unvisualizedAlertList;
            model.VisualizedAlertList = visualizedAlertList;

            return model;
        }
    }
}

FileToEmailLinker/Models/Services/Dashboard/IDashboardService.cs
using FileToEmailLinker.Models.ViewModels.Dashboard;

namespace FileToEmailLinker.Models.Services.Dashboard
{
    public interface IDashboardService
    {
        Task<Dictionary<DateOnly, ICollection<Entities.Schedulation>>> GetUpcomingSchedulations();
        Task<Dictionary<DateOnly, ICollection<Entities.Schedulation>>> GetSchedulationByDate(DateOnly date);
        Task<DashboardViewModel> GetDashboardViewModel();
    }
}

FileToEmailLinker/Controllers/DashboardController.cs
using FileToEmailLinker.Models.Entities;
using FileToEmailLinker.Models.Services.Alert;
using FileToEmailLinker.Models.Services.Dashboard;
using FileToEmailLinker.Models.ViewModels.Dashboard;
using Microsoft.AspNetCore.Mvc;

namespace FileToEmailLinker.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardService dashboardService;
        private readonly IAlertService alertService;

        public DashboardController(IDashboardService dashboardService, IAlertService alertService)
        {
            this.dashboardService = dashboardService;
            this.alertService = alertService;
        }
        public async Task<IActionResult> Index()
        {
            DashboardViewModel model = await dashboardService.GetDashboardViewModel();

            return View(model);
        }

        public async Task<IActionResult> SearchByDate(DateOnly dateSearch)
        {
            if(dateSearch != DateOnly.MinValue)
            {
                var requiredSchedulations = await dashboardService.GetSchedulationByDate(dateSearch);

                return PartialView("/Views/Shared/Dashboard/_DashboardRows.cshtml", requiredSchedulations);
            }
            return Ok(null);
        }

        public async Task<IActionResult> ClearDateSearch()
        {
            var upcomingSchedulations = await dashboardService.GetUpcomingSchedulations();

            return PartialView("/Views/Shared/Dashboard/_DashboardRows.cshtml", upcomingSchedulations);
        }

        public async Task<IActionResult> CheckAlert(int id)
        {
            await alertService.CheckAlertAsync(id);
            ICollection<Alert> alerts = await alertService.GetUnvisualizedAlertListAsync();
            //UpdateBadgeCount(alerts.Count);

            return PartialView("Dashboard/_SegnalazioniRows", alerts);
        }

        public async Task<IActionResult> CheckAlertAndReload(int id)
        {
            DashboardViewModel dashboardViewModel = await alertService.CheckAlertAndReloadModel(id);

            return PartialView("Dashboard/_AllSegnalazioniTables", dashboardViewModel);
        }

        public async Task<IActionResult> RemoveAlertAndReload(int id)
        {
            AlertsListViewModel alertsListViewModel = await alertService.RemoveAlertAndReload(id);
            return PartialView("Dashboard/_VisualizedAlertTable", alertsListViewModel);
        }

        public async Task<IActionResult> GetVisualizedAlerts()
        {
            ICollection<Alert> alerts = await alertService.GetVisualizedAlertListAsync();

            return PartialView("Dashboard/_VisualizedSegnalazioniRows", alerts);
        }

        public async Task<IActionResult> GetUnvisualizedAlertListNthPage(int page)
        {
            AlertsListViewModel alertsListViewModel = await alertService.GetUnvisualizedAlertListViewModelAsync(page, 10);
            return PartialView("Dashboard/_UnvisualizedAlertTable", alertsListViewModel);
        }

        public async Task<IActionResult> GetVisualizedAlertListNthPage(int page)
        {
            AlertsListViewModel alertsListViewModel = await alertService.GetVisualizedAlertListViewModelAsync(page, 10);
            return PartialView("Dashboard/_VisualizedAlertTable", alertsListViewModel);
        }

        //public async Task<IActionResult> UpdateBadgeCount()
        //{
        //    ICollection<Alert> alerts = await alertService.GetUnvisualizedAlertListAsync();

        //    return PartialView("Dashboard/_SegnalazioniBadge", alerts.Count());
        //}
    }
}

FileToEmailLinker/Controllers/MailingPlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FileToEmailLinker.Data;
using FileToEmailLinker.Models.Entities;
using FileToEmailLinker.Models.Services.MailingPlan;
using FileToEmailLinker.Models.InputModels.MailPlans;
using FileToEmailLinker.Models.InputModels.Schedulations;
using Org.BouncyCastle.Bcpg;
using FileToEmailLinker.Models.ViewModels;

namespace FileToEmailLinker.Controllers
{
    public class MailingPlansController : Controller
    {
        private readonly FileToEmailLinkerContext _context;
        private readonly IMailingPlanService mailingPlanService;

        public MailingPlansController(FileToEmailLinkerContext context, IMailingPlanService mailingPlanService)
        {
            _context = context;
            this.mailingPlanService = mailingPlanService;
        }

        // GET: MailingPlans
        public async Task<IActionResult> Index(int page = 1, int limit = 10, string search = "")
        {
            MailingPlanListViewModel model = await mailingPlanService.GetMailingPlanListViewModelAsync(page, limit, search);

            return View(model);
        }

        // GET: MailingPlans/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var mailingPlan = await mailingPlanService.GetMailingPlanByIdAsync(id);
            if(mailingPlan == null)
            {
                TempData["ErrorMessage"] = "Non è stato possibile recuperare la pianificazione cercata";
                return RedirectToAction(nameof(Index));
            }

            return View(mailingPlan);
        }

        // GET: MailingPlans/Create
        public async Task<IActionResult> Create()
        {
            //ViewData["SchedulationId"] = new SelectList(_context.Set<Schedulation>(), "Id", "Name");
            MailPlanInputModel mailingPlanInputModel = await mailingPlanService.CreateMailPlanInputModelAsync();
            return View(mailingPlanInputModel);
        }

        // POST: MailingPlans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MailPlanInputModel model) //MailPlanCreateInputModel model
        {
            ValidateSchedules(model);
            if (ModelState.IsValid)
            {
                MailingPlan mailingPlan = await mailingPlanService.CreateMailingPlanAsync(model);
                TempData["ConfirmationMessage"] = "Pianificazione creata con successo";
                return RedirectToAction(nameof(Details), new { id = mailingPlan.Id });
            }

            string messages = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));

            MailPlanInputModel restoredModel = await mailingPlanService.RestoreModelForCreationAndEditing(model);
            return View(restoredModel);
        }

        private void ValidateSchedules(MailPlanInputModel model)
        {
            if (model.WeeklySchedulation == null && model.MonthlySchedulation == null)
            {
                ModelState.AddModelError(nameof(model.WeeklySchedulation), "Non sono stati selezionati giorni per l'invio");
            }
            else if (model.MonthlySchedulation != null && !DayAndMonthSelected(model.MonthlySchedulation))
            {
                ModelState.AddModelError(nameof(model.MonthlySchedulation), "Selezionare almeno un giorno e un mese per la schedulazione mensile");
            }
        }

        private bool DayAndMonthSelected(MonthlyScheduleInputModel monthlySchedulation)
        {
            return (
                (monthlySchedulation.One ||
                monthlySchedulation.Two ||
                monthlySchedulation.Three ||
                monthlySchedulation.Four ||
                monthlySchedulation.Five ||
                monthlySchedulation.Six ||
                monthlySchedulation.Seven ||
                monthlySchedulation.Eight ||
                monthlySchedulation.Nine ||
                monthlySchedulation.Ten ||
                monthlySchedulation.Eleven ||
                monthlySchedulation.Twelve ||
                monthlySchedulation.Thirteen ||
                monthlySchedulation.Fourteen ||
                monthlySchedulation.Fifteen ||
                monthlySchedulation.Sixteen ||
                monthlySchedulation.Seventeen ||
                monthlySchedulation.Eighteen ||
                monthlySchedulation.Nineteen ||
                monthlySchedulation.Twenty ||
                monthlySchedulation.Twentyone ||
                monthlySchedulation.Twentytwo ||
                monthlySchedulation.Twentythree ||
                monthlySchedulation.Twentyfour ||
                monthlySchedulation.Twentyfive ||
                monthlySchedulation.Twentysix ||
                monthlySchedulation.Twentyseven ||
                monthlySchedulation.Twentyeight ||
                monthlySchedulation.Twentynine ||
                monthlySchedulation.Thirty ||
                monthlySchedulation.Thirtyone) &&
                (monthlySchedulation.January||
                monthlySchedulation.February||
                monthlySchedulation.March||
                monthlySchedulation.April||
                monthlySchedulation.May||
                monthlySchedulation.June||
                monthlySchedulation.July||
                monthlySchedulation.August||
                monthlySchedulation.September||
                monthlySchedulation.October||
                monthlySchedulation.November||
                monthlySchedulation.December));
        }

        public IActionResult AddWeeklyScheduleInputModel()
        {
            WeeklyScheduleInputModel model = new();
            return PartialView("/Views/Schedulations/_WeeklySchedulation.cshtml", model);
        }

        public IActionResult AddMonthlyScheduleInputModel()
        {
            MonthlyScheduleInputModel model = new();
            return PartialView("/Views/Schedulations/_MonthlySchedulation.cshtml", model);
        }

        // GET: MailingPlans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if(id is null)
            {
                ViewData["ErrorMessage"] = "Errato riferimento per la programmazione";
                return View(nameof(Index));
            }
            MailingPlan mailingPlan = await mailingPlanService.GetMailingPlanByIdAsync((int)id);
            if(mailingPlan is null)
            {
                ViewData["ErrorMessage"] = "Non è possibile recuperare la programmazione cercata";
                return View(nameof(Index));
            }
            MailPlanInputModel mailPlanInputModel = await mailingPlanService.GetMailingPlanEditModelAsync((int)id);

            return View(mailPlanInputModel);
        }

        // POST: MailingPlans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MailPlanInputModel model)
        {
            ValidateSchedules(model);
            if (ModelState.IsValid)
            {
                MailingPlan mailingPlan = await mailingPlanService.EditMailingPlanAsync(model);
                TempData["ConfirmationMessage"] = "Pianificazione modificata con successo";
                return RedirectToAction(nameof(Details), new { id = mailingPlan.Id });
            }

            string messages = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));

            MailPlanInputModel restoredModel = await mailingPlanService.RestoreModelForCreationAndEditing(model);
            return View(restoredModel);
        }

        // GET: MailingPlans/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var mailingPlan = await mailingPlanService.GetMailingPlanByIdAsync(id);
            if (mailingPlan == null)
            {
                TempData["ErrorMessage"] = "Non è stato possibile recuperare la pianificazione cercata";
                return RedirectToAction(nameof(Index));
            }

            return View(mailingPlan);
        }

        // POST: MailingPlans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mailingPlan = await mailingPlanService.GetMailingPlanByIdAsync(id);
            if (mailingPlan == null)
            {
                TempData["ErrorMessage"] = "Non è stato possibile recuperare la pianificazione cercata";
            }
            else
            {
                await mailingPlanService.DeleteMailingPlanAsync(mailingPlan);
                TempData["ConfirmationMessage"] = "Pianificazione eliminata correttamente";
            }

            return RedirectToAction(nameof(Index));
        }

        private bool MailingPlanExists(int id)
        {
          return (_context.MailingPlan?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FileToEmailLinker/Customizations/PaginationBarViewComponent.cs
using FileToEmailLinker.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FileToEmailLinker.Customizations
{
    public class PaginationBarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPaginationInfo model)
        {
            if (!string.IsNullOrEmpty(model.Action))
            {
                return View("ForReplacement", model);
            }
            return View("Default",model);
        }
    }
}

FileToEmailLinker/Views/Shared/Dashboard/_AllSegnalazioniTables.cshtml
@using FileToEmailLinker.Models.ViewModels.Dashboard;
@model DashboardViewModel

<div class="row">
    <div class="col-auto position-relative">
        <h3>Segnalazioni</h3>
        <h6 id="segnalazioniBadge">
            <partial name="Dashboard/_SegnalazioniBadge" model="@Model.UnvisualizedAlertList.Alerts.TotalCount"></partial>
        </h6>
    </div>
</div>
<div id="alertTable">
    <div id="unvisualizedAlertTable">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th scope="col">Messaggio</th>
                    <th scope="col">Data</th>
                    <th scope="col">Livello</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="segnalazioniRows">
                <partial name="Dashboard/_SegnalazioniRows" model="@Model.UnvisualizedAlertList.Alerts.Results"></partial>
            </tbody>
        </table>
        <vc:pagination-bar model="@Model.UnvisualizedAlertList"></vc:pagination-bar>
    </div>

    <div class="row row-cols-2 mb-2">
        <div class="col-auto">
            <h5>Visualizzate</h5>
        </div>
        <div class="col">
            <button class="btn btn-outline-primary btn-sm ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#visualizedAlertTable" aria-expanded="false" aria-controls="visualizedAlertTable">
                <i class="bi bi-arrows-collapse"></i>
            </button>
        </div>
    </div>
    <div class="collapse" id="visualizedAlertTable">
        <partial name="Dashboard/_VisualizedAlertTable" model="@Model.VisualizedAlertList"></partial>
    </div>
</div>

FileToEmailLinker/Views/Shared/Dashboard/_DashboardRows.cshtml
@model Dictionary<DateOnly,ICollection<Schedulation>>

@foreach (KeyValuePair<DateOnly, ICollection<Schedulation>> entry in Model)
{
    <tr>
        <td class="fw-bolder pt-2">@entry.Key</td>
        <td>
            @if(entry.Value != null && entry.Value.Count > 0)
            {
                <ul class="list-group list-group-flush">
                    @foreach (var sched in entry.Value)
                    {
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-sm-2 fst-italic">
                                    @sched.Time
                                </div>
                                <div class="col">
                                    <a asp-controller="MailingPlans" asp-action="Details" asp-route-id="@sched.MailingPlan.Id"><i class="bi bi-box-arrow-up-right me-2"></i></a>
                                    @sched.MailingPlan.Name
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            }
            else
            {
                <span>Nessuna schedulazione in questa data</span>
            }
        </td>
    </tr>
}

FileToEmailLinker/Views/Shared/Dashboard/_SegnalazioniBadge.cshtml
@model int
<span id="badgeCount" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">@Model</span>

FileToEmailLinker/Views/Shared/Dashboard/_SegnalazioniRows.cshtml
@model ICollection<Alert>

@foreach (var segnalazione in Model)
{
    <tr>
        <td>@segnalazione.Message</td>
        <td>@segnalazione.DateTime</td>
        <td>@segnalazione.AlertSeverity</td>
        <td>
            <a asp-action="CheckAlertAndReload" 
                asp-route-id="@segnalazione.Id" 
                data-ajax="true" 
                data-ajax-mode="replace" 
                data-ajax-update="#allSegnalazioniTables"><i class="bi bi-check-circle"></i></a>
        </td>
    </tr>
}

FileToEmailLinker/Views/Shared/Dashboard/_UnvisualizedAlertTable.cshtml
@using FileToEmailLinker.Models.ViewModels.Dashboard;
@model AlertsListViewModel;

<table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">Messaggio</th>
            <th scope="col">Data</th>
            <th scope="col">Livello</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="segnalazioniRows">
        <partial name="Dashboard/_SegnalazioniRows" model="@Model.Alerts.Results"></partial>
    </tbody>
</table>
<vc:pagination-bar model="@Model"></vc:pagination-bar>

FileToEmailLinker/Views/Shared/Dashboard/_VisualizedAlertTable.cshtml
@using FileToEmailLinker.Models.ViewModels.Dashboard;
@model AlertsListViewModel;

<table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">Messaggio</th>
            <th scope="col">Data</th>
            <th scope="col">Livello</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="visualizedAlertRows">
        <partial name="Dashboard/_VisualizedSegnalazioniRows" model="@Model.Alerts.Results"></partial>
    </tbody>
</table>
<vc:pagination-bar model="@Model"></vc:pagination-bar>

FileToEmailLinker/Views/Shared/Dashboard/_VisualizedSegnalazioniRows.cshtml
@model ICollection<Alert>

@foreach (var segnalazione in Model)
{
    <tr>
        <td>@segnalazione.Message</td>
        <td>@segnalazione.DateTime</td>
        <td>@segnalazione.AlertSeverity</td>
        <td>
            <a asp-action="RemoveAlertAndReload"
                asp-route-id="@segnalazione.Id"
                data-ajax="true"
                data-ajax-mode="replace"
               data-ajax-update="#visualizedAlertTable" style="color:red"><i class="bi bi-trash3"></i></a>
        </td>
    </tr>
}